manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  remotes:
    - name: the-blob
      url-base: https://github.com/dapetcu21/the-blob-zmk-module
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: the-blob
      remote: the-blob
  self:
    path: config
